services:

  release-notes:
    build:
      context: .
      dockerfile: ReleaseNotes.Docker/dockerfile
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - JwtOptions__Secret=placeholder-placeholder-placeholder
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres;
      - Elastic__TcpSink=tcp://logstash:5044
    depends_on:
      - postgres
    networks:
      - releasenotes_network

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - releasenotes_network
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - releasenotes_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - releasenotes_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.1
    ports:
      - 5044:5044
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - releasenotes_network

networks:
  releasenotes_network:
    driver: bridge
