apiVersion: apps/v1
kind: Deployment
metadata:
  name: releasenotes-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: releasenotes-deployment
  template:
    metadata:
      labels:
        app: releasenotes-deployment
    spec:
      containers:
        - name: releasenotes-deployment
          image: 'danielmigchels/releasenotes:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: releasenotes-secret